<?php
/**
 *    Copyright 2018 Humanswitch
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
?>
<?php if ($this->isEnabled() && $this->validateJson()): ?>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function (event) {
            if (typeof ConsentCookie !== "undefined") {
                window.ConsentCookie.init(<?php echo $this->getConfiguration() ?>);

                var CCInitEvent = new CustomEvent('CCInit', {
                    detail: {
                        ConsentCookie: ConsentCookie
                    }
                });

                window.dispatchEvent(CCInitEvent);
            }
        });
    </script>
<?php endif; ?>



